2024-11-04 22:15:19.344661: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:15:24.403042: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:15:29.063959: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:16:46.478452: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:17:37.786906: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:17:42.682057: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:17:47.498831: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:19:00.431403: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:19:54.866100: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:20:00.251088: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:20:05.917617: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:21:24.936026: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:22:17.098133: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:22:21.889743: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:22:26.669033: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:23:40.633186: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:24:27.654827: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:24:32.232126: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:24:37.070072: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:25:47.795958: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:26:55.839818: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:27:00.805294: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:27:05.565055: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:28:23.790639: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:29:15.084425: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:29:19.703856: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:29:23.885868: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:30:50.527446: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:31:33.519735: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:31:41.305989: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:31:49.119251: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:33:17.895448: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:34:12.393584: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:34:19.783206: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:34:27.460957: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:35:35.732268: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
2024-11-04 22:36:40.948191: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:36:45.734933: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:36:50.804547: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
Traceback (most recent call last):
  File "/data1/wuguojia/data/mhc_benchmark/tools/DeepNetBim/src/predict.py", line 62, in <module>
    prediction = model_bind.predict([np.array(peptides),np.array(network)])
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/data1/wuguojia/software/miniconda/envs/deepnetbim/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 3 dimensions, but got array with shape (0, 1)
2024-11-04 22:38:01.605697: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
Using TensorFlow backend.
	Command being timed: "bash /home/wuguojia/biocode/mhc_benchmark/speed_command/deepnetbim_command.sh"
	User time (seconds): 1414.82
	System time (seconds): 34.31
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 24:03.44
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 426464
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 377
	Minor (reclaiming a frame) page faults: 4275475
	Voluntary context switches: 22948
	Involuntary context switches: 5531740
	Swaps: 0
	File system inputs: 918560
	File system outputs: 1032
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
